name: "Corn Job"
on:
  schedule:
  - cron: '32 * * * *'

jobs:
  corn-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v4