name: Cypress tests
on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]
jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install Dependencies
        run: |
          npm install cypress --save-dev
      
      - name: My Experiments
        run: |
          npx cypress run --headless
