name: Cypress tests
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "*/2 * * * *"
jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
          headless: true
