name: Cypress tests
on:
  workflow_dispatch:
  pull_request:
    branches: ['main']
jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Cypress run
        uses: cypress-io/github-action@v4
